# Generated by Django 3.2.7 on 2021-09-16 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_status', models.IntegerField(choices=[(1, 'Open'), (2, 'Close')])),
                ('course_code', models.CharField(max_length=5)),
                ('course_name', models.CharField(max_length=128)),
                ('course_semester', models.IntegerField(choices=[(1, 'Semester1'), (2, 'Semester2')])),
                ('course_quota', models.IntegerField()),
                ('students', models.ManyToManyField(blank=True, related_name='user_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('users', models.ManyToManyField(blank=True, related_name='reg_student', to='regs.Reg')),
            ],
        ),
    ]
